#!/usr/bin/zsh

command_name=$1
program_name=$2

wmctrl -R $program_name
if [ $? -eq 1 ]; then
	for windowIdPid in $(wmctrl -l -p | awk '{print $1 "-" $3}'); do
		ids=("${(@s/-/)windowIdPid}")
		windowId=$ids[1]
		pid=$ids[2]
		if [ "$(ps $pid | grep $program_name)" != "" ]; then
			wmctrl -i -R $windowId
			exit
		fi
	done
else
	exit
fi

$command_name
