#! /usr/bin/env python3

import sys

if len(sys.argv) != 2:
	print("No expression provided. Usage: pyawk EXPR", file=sys.stderr)
	sys.exit(1)

func = eval("lambda ln: print(ln.{})".format(sys.argv[1]))
for ln in sys.stdin:
	func(ln)
